### ISSUE TITLE
Add sync Application logic

### ISSUE THREAD

**Issue by maruina** [Skyscanner/argocd-progressive-rollout#22]
Add the logic to tell ArgoCD to sync a target Application. We should document on which approach we are taking before implementing it.

Options:
- Use the `argocd` CLI
  - PRO: easy to use, see https://github.com/maruina/argocd-progressive-rollout-controller/blob/main/controllers/progressiverollout_controller.go#L229
  - PRO: (almost) idempotent, it has an error code when re-trying an Application that is already syncing
  - CON: need to manage the authentication to the ArgoCD server, e.g. token lifecycle
  - CON: embed and keep in sync the CLI in the docker image
- Use the code behind the CLI at https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go#L1229
	- PRO: no need to manage the CLI
	- PRO: everything is done in code and re-use ArgoCD code
	- CON: authentication to the ArgoCD server
- Use annotation `argocd.argoproj.io/refresh` as per https://github.com/argoproj/argo-cd/blob/13b9b92c991874252e9e01dd8e94e69cb526827b/common/common.go#L121
  - PRO: very easy to use, very little code to write
  - CON: idempotency more difficult

**Comment by sledigabel** [comment]
Fixed via #44
