### ISSUE TITLE
Discuss pointer vs value semantics, agree and refactor

### ISSUE THREAD

**Issue by sledigabel** [Skyscanner/argocd-progressive-rollout#33]
The operator has a mix of pointer semantics vs value semantics.
More than the decision about _why_, we need to be consistent and not flip flop between one or the other.

https://github.com/Skyscanner/argocd-progressive-rollout/pull/25/files#diff-b1a5cf22f2be07477047c7c268c9a2077f75c3fdadc285eb862dab8bc3aaad31R293
https://github.com/Skyscanner/argocd-progressive-rollout/pull/25/files#diff-c3753ff27e79b7da6571efc4fffc45e729b031a39337eec9b22a04425bbd69f0R12

https://tour.golang.org/methods/8
https://www.ardanlabs.com/blog/2017/06/design-philosophy-on-data-and-semantics.html

**Comment by maruina** [comment]
We discussed and agree to keep:
- pointer semantic for the controller and reconciler
- value semantic for everything else

So we need to change only this method: https://github.com/Skyscanner/argocd-progressive-rollout/blob/main/controllers/progressiverollout_controller.go#L293
